sudo: false
language: node_js
node_js:
  - '6'
  - '8'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - unzip
      - g++-4.8
script: ./travis.sh
cache:
  directories:
  - cli/.flow-bins-cache
