sudo: false
language: node_js
node_js:
- '5.1'
addons:
  apt:
    packages:
    - unzip
script: cd npm && npm install && npm run build && node dist/cli.js validate-defs && node dist/cli.js run-tests
cache:
  directories:
  - npm/flow-bins
